### ISSUE TITLE
The member extents_ is not available if HAVE_MPI is not set.

### ISSUE THREAD

**Issue by maxkahnt** [spraetor/dune-vtk#1]
https://github.com/spraetor/dune-vtk/blob/eb3dea8e5044c5808d0d2b407aff59f8c03f46e4/dune/vtk/datacollectors/structureddatacollector.hh#L168

**Comment by spraetor** [comment]
Thanks for pointing out this.

**Comment by maxkahnt** [comment]
I should have written this as a first sentence to the issue: I appreciate the work you have done!
